nmap <C-L> :Telescope live_grep<CR>
nmap <leader>gt :Telescope git_status<CR>
nmap <leader>cm :Telescope git_commits<CR>
nmap <leader>fh :Telescope help_tags<CR>
nmap <leader>fo :Telescope oldfiles<CR>
nmap <C-p> :Telescope find_files<CR>
nmap <C-b> :Telescope buffers<CR>
nmap <leader>r :Telescope lsp_references<cr>
nmap <leader>i :Telescope lsp_implementations<cr>
